# Generated by Django 3.2.9 on 2022-12-28 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(choices=[('The Classics', 'The Classics'), ('The Trenders', 'The Trenders'), ('The One-Hit Wonder', 'The One-Hit Wonder'), ('The Social Media', 'The Social Media'), ('The Series', 'The Series'), ('The Niche', 'The Niche'), ('The Obscurity', 'The Obscurity'), ('The Comics', 'The Comics'), ('Other', 'Other')], max_length=30)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Memename', models.CharField(max_length=30)),
                ('Caption', models.CharField(max_length=200)),
                ('Image', models.ImageField(upload_to='memes')),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meme.categorie')),
            ],
        ),
    ]
