# Generated by Django 3.2.9 on 2022-12-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='Image',
            field=models.ImageField(upload_to='media/memes'),
        ),
    ]
